services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql\
    networks:
      - private
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
  backend:
    build:
      args:
        # disponible mientras se este creando la imagen
        # - NODE_ENV=development
            # creo que asi lo hago mas dinamico
          - NODE_ENV=${NODE_ENV}
      context: backend
      target: development
    # command: npm run start-watch
    environment:
      # say backend to use development environment
      - NODE_ENV=${NODE_ENV}
      # local development
      - DATABASE_DB=${DATABASE_DB}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      # staging environment
      - STAGING_DATABASE_HOST=${STAGING_DATABASE_HOST}
      - STAGING_DATABASE_PORT=${STAGING_DATABASE_PORT}
      - STAGING_DATABASE_DB=${STAGING_DATABASE_DB}
      - STAGING_DATABASE_USER=${STAGING_DATABASE_USER}
      - STAGING_DATABASE_PASSWORD=${STAGING_DATABASE_PASSWORD}
    ports:
      - 80:80
      - 9229:9229
      - 9230:9230
    secrets:
      - db-password
    volumes:
      - ./backend/src:/code/src:ro
      - ./backend/package.json:/code/package.json
      - ./backend/package-lock.json:/code/package-lock.json
      - back-notused:/opt/app/node_modules
    networks:
      - public
      - private
    depends_on:
      - db
  frontend:
    build:
      context: frontend
      target: development
    environment:
      - BACKEND_HOST=${BACKEND_HOST}
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/code/src
      - /code/node_modules
    networks:
      - public
    depends_on:
      - backend
networks:
  public:
  private:
volumes:
  back-notused:
  db-data:
secrets:
  db-password:
    file: db/password.txt
