name: Deploy to ECR

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          echo " hello this github actions is working, teuddy"

  # sudo apt-get install -y docker-compose
  # - name: Login to ECR
  #   id: login-ecr
  #   uses: aws-actions/amazon-ecr-login@v1
  #   with:
  #     registry: <your-ecr-registry>

  # - name: Build and push images
  #   run: |
  #     docker-compose build
  #     docker-compose push
